bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /Odometry
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code


velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [1.0, 0.0, 1.0]
    min_velocity: [-0.3, 0.0, -1.0]
    max_accel: [1.5, 0.0, 2.5]
    max_decel: [-1.5, 0.0, -2.5]
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0 

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false
    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 1000
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.4
      vx_max: 1.0
      vx_min: -0.3
      vy_max: 0.0
      wz_max: 1.0
      ax_max: 3.0
      ax_min: -3.0
      ay_min: 0.0
      ay_max: 0.0
      az_max: 3.5
      iteration_count: 1
      prune_distance: 1.5
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive" #"Omni"
      visualize: true #True in debug mode only since it uses coputational ressources
      publish_optimal_trajectory: true
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      publish_critics_stats: true
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      TrajectoryValidator:
        plugin: "mppi::DefaultOptimalTrajectoryValidator"
        collision_lookahead_time: 2.0
        consider_footprint: true
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic"]
      #critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic","PreferForwardCritic", "ObstaclesCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5
      # ObstaclesCritic:
      #   enabled: true
      #   cost_power: 1
      #   repulsion_weight: 1.5 #f this penalty is too high, the robot will slow significantly when entering cost-space from non-cost space or jitter in narrow corridors.
      #   critical_weight: 20.0
      #   consider_footprint: true #use the full footprint information if consider_footprint = true, though comes at an increased compute cost.
      #   collision_cost: 10000.0
      #   collision_margin_distance: 0.12
      #   near_goal_distance: 0.5
      #   inflation_radius: 0.6 # (only in Humble)
      #   cost_scaling_factor: 4.0 # (only in Humble)
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 0.5
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 8.0
      publish_frequency: 8.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 7
      height: 7
      resolution: 0.05
      transform_tolerance: 0.2
      footprint: "[[0.36, 0.165], [0.36, -0.165], [-0.36, -0.165], [-0.36, 0.165]]"
      plugins: ["obstacle_layer","inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 0.83
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 8.0 
          obstacle_max_range: 3.5
          observation_persistence: 0.0
          inf_is_valid: true 
        scan1:
          topic: /utlidar/scan
          max_obstacle_height: 0.83
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 8.0 
          obstacle_max_range: 3.0
          observation_persistence: 0.0
          inf_is_valid: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.6
        always_send_full_costmap: true
        introspection_mode: "disabled"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 1.0
      publish_frequency: 1.0
      transform_tolerance: 0.3
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[0.36, 0.165], [0.36, -0.165], [-0.36, -0.165], [-0.36, 0.165]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["obstacle_layer","static_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 4.0
        inflation_radius: 0.6
      always_send_full_costmap: true

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D" # In Iron and older versions, "/" was used instead of "::"
      tolerance: 0.125                      # tolerance for planning if unable to reach exact pose, in meters
      downsample_costmap: false             # whether or not to downsample the map
      downsampling_factor: 1                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: true                   # allow traveling in unknown space
      max_iterations: 1000000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000      # maximum number of iterations to attempt to reach goal once in tolerance
      max_planning_time: 2.0                # max time in s for planner to plan, smooth
      cost_travel_multiplier: 2.0           # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin" # In Iron and older versions, "/" was used instead of "::"
    backup:
      plugin: "nav2_behaviors/BackUp" # In Iron and older versions, "/" was used instead of "::"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      backup.minimum_speed: 0.3
    wait:
      plugin: "nav2_behaviors/Wait" # In Iron and older versions, "/" was used instead of "::"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    waypoint_task_executor_plugins: ["wait_at_waypoint", "drive_to_waypoint"]
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      wait_duration: 0.0
    drive_to_waypoint:
      plugin: "nav2_waypoint_follower::DriveToWaypoint"

collision_monitor:
  ros__parameters:
    enabled: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel"
    cmd_vel_out_topic: "cmd_vel_out"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 2.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    enable_stamped_cmd_vel: False  # False for Jazzy or older
    use_realtime_priority: false
    polygons: ["PolygonStop"]
    PolygonStop:
      type: "polygon"
      points: [0.37, 0.175,0.37, -0.175,0.00, -0.175,0.00, 0.175]
      action_type: "stop"
      max_points: 3  # max_points: 3 for Humble
      visualize: True
      polygon_pub_topic: "polygon_stop"
      enabled: True
    # PolygonSlow:
    #   type: "polygon"
    #   points: [0.5, 0.30,0.5, -0.30,0.0, -0.30,0.0, 0.30]
    #   action_type: "slowdown"
    #   max_points: 3  # max_points: 3 for Humble
    #   slowdown_ratio: 0.2
    #   visualize: True
    #   polygon_pub_topic: "polygon_slowdown"
    #   enabled: True
    # PolygonLimit:
    #   type: "polygon"
    #   points: "[[0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 0.5]]"
    #   action_type: "limit"
    #   max_points: 3  # max_points: 3 for Humble
    #   linear_limit: 0.4
    #   angular_limit: 0.5
    #   visualize: True
    #   polygon_pub_topic: "polygon_limit"
    #   enabled: True
    # FootprintApproach:
    #   type: "polygon"
    #   action_type: "approach"
    #   footprint_topic: "/local_costmap/published_footprint"
    #   time_before_collision: 2.0
    #   simulation_time_step: 0.02
    #   min_points: 5  # max_points: 5 for Humble
    #   visualize: False
    #   enabled: True
    # VelocityPolygonStop:
    #   type: "velocity_polygon"
    #   action_type: "stop"
    #   min_points: 6
    #   visualize: True
    #   enabled: True
    #   polygon_pub_topic: "velocity_polygon_stop"
    #   velocity_polygons: ["rotation", "translation_forward", "translation_backward", "stopped"]
    #   holonomic: false
    #   rotation:
    #     points: "[[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]"
    #     linear_min: 0.0
    #     linear_max: 0.05
    #     theta_min: -1.0
    #     theta_max: 1.0
    #   translation_forward:
    #     points: "[[0.35, 0.3], [0.35, -0.3], [-0.2, -0.3], [-0.2, 0.3]]"
    #     linear_min: 0.0
    #     linear_max: 1.0
    #     theta_min: -1.0
    #     theta_max: 1.0
    #   translation_backward:
    #     points: "[[0.2, 0.3], [0.2, -0.3], [-0.35, -0.3], [-0.35, 0.3]]"
    #     linear_min: -1.0
    #     linear_max: 0.0
    #     theta_min: -1.0
    #     theta_max: 1.0
      # This is the last polygon to be checked, it should cover the entire range of robot's velocities
      # It is used as the stopped polygon when the robot is not moving and as a fallback if the velocity
      # is not covered by any of the other sub-polygons
      # stopped:
      #   points: "[[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25, 0.25]]"
      #   linear_min: -1.0
      #   linear_max: 1.0
      #   theta_min: -1.0
      #   theta_max: 1.0
    observation_sources: ["scan"]
    scan:
      source_timeout: 0.2
      type: "scan"
      topic: "/scan"
      enabled: True
    # pointcloud:
    #   type: "pointcloud"
    #   topic: "/intel_realsense_r200_depth/points"
    #   transport_type: "raw"  # raw or/ with compression (zlib, draco, zstd)
    #   min_height: 0.1
    #   max_height: 0.5
    #   min_range: 0.2
    #   enabled: True
    # costmap:
    #   type: "costmap"   # relative, respects namespaces
    #   topic: "local_costmap/costmap"
    #   cost_threshold: 254
    #   enabled: True
    #   treat_unknown_as_obstacle: True

